package com.example.thetrek.db;

public class RewardStrings {
    private static final String[] progressArray = {
            "You got this",
            "WOW",
            "Keep going!",
            "You're on the right track",
            "Amazing job!",
            "Making progress",
            "One step at a time",
            "Great effort!",
            "Halfway there",
            "Stay focused",
            "Almost done!",
            "Believe in yourself",
            "You're getting closer",
            "Impressive work!",
            "Keep pushing forward",
            "Don't give up",
            "You can do it",
            "Just a little more",
            "Incredible!",
            "Keep it up",
            "You're doing great",
            "Fantastic!",
            "Getting better",
            "Stay determined",
            "Inspiring!",
            "Onward and upward",
            "Bravo!",
            "You're unstoppable",
            "Persevere!",
            "Getting closer to your goal",
            "Well done",
            "Making it happen",
            "You're awesome!",
            "Keep the momentum",
            "Just a few more steps",
            "You're making a difference",
            "Excellent progress",
            "You're a star",
            "Almost there",
            "You're doing fantastic",
            "Keep on going",
            "You're incredible",
            "You're unstoppable",
            "You've got this",
            "Keep up the good work",
            "Success is near",
            "You're on fire",
            "No stopping you",
            "Keep striving",
            "Unbelievable progress",
            "Keep climbing",
            "You're a champion",
            "You're a rockstar",
            "The finish line is in sight",
            "Way to go!",
            "You're a winner",
            "Keep the faith",
            "You're on the right path",
            "You're a shining star",
            "Just keep swimming",
            "You're an inspiration",
            "Amazing effort",
            "You're doing splendidly",
            "Don't stop now",
            "You're making waves",
            "You're doing extraordinary",
            "Keep aiming higher",
            "You're on a roll",
            "Spectacular job",
            "You're doing remarkable",
            "Never give up",
            "You're making it happen",
            "You're on your way",
            "You're phenomenal",
            "You're crushing it",
            "You're outstanding",
            "Keep chasing your dreams",
            "You're doing beautifully",
            "You're on the right road",
            "You're on the verge of success",
            "You're exceeding expectations",
            "You're on the cusp of greatness",
            "You're on the right course",
            "You're on the brink of victory",
            "You're reaching new heights",
            "You're making history",
            "You're on the right trajectory",
            "You're on the path to greatness",
            "You're approaching the pinnacle",
            "You're ascending to new levels",
            "You're on the road to triumph",
            "You're on the threshold of glory",
            "You're conquering challenges",
            "You're on the journey to success",
            "You're on the track to victory",
            "You're on the precipice of achievement",
            "You're advancing with determination",
            "You're on the brink of success",
            "You're on the verge of triumph",
            "You're making significant strides",
            "You're on the verge of a breakthrough",
            "You're on the brink of accomplishment",
            "You're progressing with purpose"
    };

    public static String[] getProgressArray() {
        return progressArray;
    }
}
